---
title: "Introduction"
# date: "2021-07-02"
output: pdf_document
geometry: margin=2.5cm
fontsize: 12pt
fontfamily: libertine
linestretch: 1.5
indent: true
---

\phantomsection
# Introduction {-}

La mondialisation a engrangé des échanges croissants à travers les frontières, avec des flux de biens et services, d'individus, de matières premières, qui rendent la communication entre les pays essentielle pour le maintien des opérations. La diplomatie est un espace privilégié et encadré pour mener ces concertations. La représentation internationale est considérée comme acquise et forte, avec des organismes supranationaux comme les Nations Unies comme terrain de rencontre et d'échange accessibles à tous les pays souverains du monde. Malgré les tensions géopolitiques toujours en mouvement, comme la rivalité entre les États-Unis et la Chine, ou bien entre la France et l'Australie, les États-Unis et le Royaume-Uni, il y a toujours des représentants officiels pour arbitrer la communication entre les partis. La montée d'organismes supranationaux et d'organisations régionales politiques et économiques telles que l'Association des nations de l'Asie du Sud-Est et le Marché commun du Sud pour plusieurs pays de l'Amérique du Sud, la présence de partis "neutres" qui accueillent les partis en conflit ou négocient en leurs noms comme la Suisse et la Norvège, font fonctionner la scène politique internationale multilatérale. Tout le monde s'y retrouve, la bienséance est requise, il est plus compliqué de se disputer quand d'autres acteurs sont présents autour de soi, chaque membre pèse le même poids en théorie. Toutefois, à la base de ces échanges internationaux, le niveau le plus essentiel de cette communauté internationale sont les relations bilatérales entre les nations, des relations qui en disent beaucoup sur un pays et ses affinités avec les autres que de grands groupes. Ces relations bilatérales sont symbolisées par l'échange de représentants et de leurs équipes comme extension du pouvoir de leurs États respectifs, qui ont une présence physique et fixe dans un pays d'accueil, et qui assurent la protection des intérêts du pays d'envoi, le transfert d'information, et bien d'autres missions. 

Multiplier son réseau d'ambassade envoie un message de puissance et de désir de partage avec l'autre. Le rayonnement d'un pays, la protection des ressortissants de son pays, l'espionnage...sont tous des arguments en faveur de la constitution d'une équipe de diplomates. Cependant, envoyer 192 missions de représentations dans 192 états membres des Nations Unies est une dépense importante que tout le monde ne peut pas se permettre de faire.

Certains pays ont les moyens et l'envie de s'implanter dans tous les pays du monde, que ce soit pour le prestige et pour affirmer sa présence dans un pays ou une région, pour envoyer un message politique, pour surveiller le pays. Certains n'ont pas les moyens mais ont l'envie. Certains ont les moyens mais n'ont pas l'envie. Certains pays sont inaccessibles directement au chagrin des autres. De ce fait, en dehors des arènes communes à des groupes de pays, le réseau de représentation internationale n'est pas complet: les relations bilatérales entre pays ne sont pas toutes existantes et les existantes ne sont pas égales entre elles. Pour compenser l'absence physique, certains pays décident d'accréditer leurs missions existantes dans un pays d'accueil donné auprès d'un ou plusieurs autres pays, multipliant la charge de travail de l'équipe sur place. D'autres délivrent l'autorisation à leurs alliés qui auraient une mission diplomatique à un endroit où les premiers seraient absents d'agir en leur nom, dans le pays d'accueil et dans les autres autour. Les recherches précédentes et certains pays présentent la représentation directe, unique et vaste comme la forme de diplomatie la plus forte, ce que je conteste dans ce mémoire. L'utilisation d'un intermédiaire permet de contourner l'impulsion de devoir conduire des liaisons sur place et partout, en centralisant les fonctions diplomatiques à un endroit. Elle offre la possibilité à de "petits" acteurs de s'insérer dans ce système considéré comme prestigieux, pour un coût moindre. Qui sont ces pays qui emploient cette pratique ? Comment se distinguent-ils des pays qui préfèrent la représentation directe et unique ?

Ce sont des missions que j'appelle "intermédiaire" dans ce mémoire: elles sont localisées dans un pays, elles effectuent leurs opérations dans celui-ci et dans d'autres en même temps. Toutefois, l'utilisation du terme "intermédiaire" présente une ambiguïté importante. Il y a les intermédiaires de ce système international qui constitue un réseau dense et avec beaucoup de liens réciproques, ainsi que la notion mathématique de centralité d'intermédiarité propre à la théorie des graphes et des réseaux et comme définie par Freeman [-@freeman1977]: elle calcule le nombre de fois qu'un noeud est sur le chemin le plus court entre deux autres noeuds du graphe. Le pays d'accueil et la mission diplomatique sont des intermédiaires "réels", on leur a consciencieusement attribué ces rôles: la centralité d'intermédiarité reflète-t-elle les décisions réfléchies d'un pays ? 

Ce mémoire veut mettre en lumière les pays "délaissés" du système des ambassades par la recherche et par leurs homologues, à travers l'analyse du réseau des ambassades multiplement accréditées. Il espère montrer que ce réseau est aussi efficace et pertinent que celui des missions uniques.

Pour répondre aux questions posées plus haut, j'utilise la base de données longitudinale _Diplometrics: Diplomatic Representation_ [-@moyer2016], du Frederick S. Pardee Center for International Futures. Cette base recense les différentes ambassades présentes dans une capitale, pour 206 pays de 1960 à 2013. Pour présenter les acteurs clefs de l'accréditation multiple, je présente plusieurs classements et une analyse en composantes principales pour visualiser les différents groupes de pays et les sous-pratiques de l'accréditation multiple. Je trouve que les pays d'Europe du Nord sont très actifs en tant que pays d'envoi et en tant que pays ciblés par ces ambassades aux grandes juridictions, tandis que les pays d'Afrique utilisent beaucoup ce mode de représentation par rapport à celui de l'ambassade unique. Je présente ensuite des cartes du réseau d'ambassades multiples à travers les décennies, puis des comparaisons entre les structures des réseaux multiples, uniques et complets. Le réseau des missions multiples s'est considérablement élargi en 30 ans, au point de rivaliser avec le réseau des missions uniques. Je conclus par des mesures de corrélations entre l'intermédiarité empirique et deux mesures de centralité de la théorie des graphes, la centralité d'intermédiarité et la centralité de degré. Je trouve que l'intermédiarité empirique ressemble plus à la centralité de degré qu'à celle d'intermédiarité.

Le mémoire est construit de la manière suivante: premièrement, j'effectue une revue de la littérature pour définir la représentation diplomatique, l'intermédiarité diplomatique et la centralité d'intermédiarité. J'y présente aussi ma question de recherche globale et mes hypothèses. Deuxièmement, je présente mes données en profondeur ainsi que la méthodologie employée. En troisième partie, j'expose les résultats que j'interpréterai dans un quatrième chapitre. Enfin, je présente mes conclusions et les pistes d'études supplémentaires.
