---
title: "Interprétations"
output:
  pdf_document:
    number_sections: true
geometry: margin=2.5cm
fontsize: 12pt
fontfamily: fourier
linestretch: 1.5
indent: true
header-includes:
  - \setlength{\parskip}{1em}
---

# Interprétations

Par rapport aux continents: l'Océanie est entièrement composée d'îles, ce qui rend l'accès difficile, d'où la nécessité de centraliser les missions diplomatiques dans un pays (en l'occurrence l'Australie) et de mener les relations inter-nations à partir de celui-ci. L'Asie compte beaucoup de pays, mon intuition est que le coût faible de la vie et l'envie de s'affirmer politiquement dans la région sont les raisons pour lesquelles il y a moins de missions multiples qu'uniques. D'un autre côté, il y a autant de pays en Europe qu'en Asie, mais il y a plus de missions multiples en Europe: l'Europe est onéreuse, posséder un bâtiment et une équipe dans chaque capitale de l'Europe est une dépense trop importante à maintenir malgré les avantages fiscaux qui viennent avec le métier, et malgré l'envie de présence qui reste forte.

Par rapport à l'Europe, beaucoup de ses grands pays n'ont pas de présence directe à l'étranger et ne reçoivent pas directement les missions des autres, ce qui est surprenant quand on prend en compte le tableau des missions uniques. On retrouve quand même quatre membres du Conseil de Sécurité dans la catégorie des pays de résidence des représentations multiples; toutefois, la Belgique était l'hôte de plus de missions multiples pendant les trois décennies étudiées. Installer son ambassade en Belgique offre la proximité avec d'autres voisins européens et avec les sièges de plusieurs instances de l'Union Européenne. C'est un lieu idéal pour négocier et récolter des informations d'ordre internationales. En plus du royaume Belge, le Royaume-Uni et la France complètent le podium des pays de résidence les plus choisis pour accueillir une ambassade aux multiples missions. On retrouve trois anciennes puissances coloniales sur lesquelles les autres nations du monde se reposent toujours pour accueillir leurs équipes de représentants, et dont l'importance est toujours significative sur la scène internationale. L'Europe reste un coeur historique et politique qui ne peut pas être évité diplomatiquement par les autres pays du monde.

Les missions multiples ne sont clairement pas favorites, sans surprise, mais sont favorisées par certains types de pays. Les îles des Caraïbes et du Pacifique et les pays d'Afrique étaient de grands expéditeurs: leurs petites populations, la distance importante entre eux et les autres, les moyens réduits, peuvent être des arguments expliquant leur présence réduite à l'étranger. Ces pays désirent tout de même maintenir des relations et élargir leur nombre de connaissance, mais en réduisant les efforts et les dépenses, d'où la remise des accréditations multiples importantes dans ces pays. Leur quantité est faible par rapport à d'autres pays très actifs dans ce réseau, les relations construites sont moins "personnalisée" avec l'autre mais au moins elles existent.

La place de l'Afrique et de ses pays dans le réseau de missions multiples méritent un détour supplémentaire: ceux-ci envoient en majorité des ambassades multiples et ils en sont majoritairement la cible au lieu de celles de missions uniques. La période étudiée marque une vague de décolonisation du continent africain: il revient aux nouveaux pays de construire leur présence internationale en raison de la disparition des pouvoirs supérieurs coloniaux qui les représentaient autrefois. C'est ainsi qu'on a pu observé la multiplication du nombre de pays d'Afrique qui participaient aux échanges diplomatiques au fil des années, par le biais des représentations multiples, pour atteindre une connection intercontinentale importante à la fin des années 80. En comparant avec les autres continents, on a pu voir que cette pratique était aussi "africaine qu'européenne". Les pays d'Afrique étaient dans le processus d'établir des pouvoirs centraux stables et permanents, leurs réserves de hauts fonctionnaires étaient peut-être limitées et étaient consacrées aux efforts nationaux plutôt qu'aux relations internationales. Petit à petit, les pays africains ont consolidé leur présence dans le monde avec les représentations multiples; un représentant diplomatique était en charge de grandes zones géographiques. La charge de travail supplémentaire oblige ces responsables à être plus compétents et à devenir des experts des politiques de plusieurs pays au lieu d'un seul. Certes, la pratique de l'accréditation multiple réduit les coûts financiers pour le pays accréditant, mais elle augmente le capital culturel qu'un individu doit acquérir pour mener ses fonctions. C'est une forme de prestige qui passe autrement inaperçue.

Les pays nordiques étaient des cibles très récurrentes des représentations multiples qui étaient principalement localisées en Suède. Le Traité de Helsinki est destiné à la représentation des pays nordiques en dehors des pays nordiques, mais il semblerait que les autres pays l'appliquent aussi en confiant à leur mission suédoise et à la Suède la tâche de communiquer avec les autres membres du Conseil Nordique. L'ACP a présenté les pays nordiques comme un bloc homogène, c'est une opinion qui est partagée dans le bloc même et en dehors. Le partage des institutions, l'existence et l'inscription d'objectifs communs, l'équivalence des systèmes d'éducation sont tous inscrits dans le traité de Helsinki. Les politiques des pays nordiques donnent l'impression qu'une grande fédération existe, fédération dont la capitale est Stockholm. Il devient alors logique de centraliser toutes les activités diplomatiques à destination de la région en Suède.


Le Luxembourg est un autre cas spécial et saillant: c'est le pays le plus prisé par les autres gouvernements du monde et son inaccessibilité est forte. Le Grand-Duché est un petit pays, peut-être n'y a-t-il pas assez de place pour s'y installer? Le Luxembourg possède aussi des sièges institutionnels de l'Union Européenne, la Commission européenne, et la Cour de justice. Je ne pensais pas que ce pays était un acteur important de la diplomatie en général, encore moins de la diplomatie multiple. Ce choix est commun à beaucoup trop de nations pour qu"il soit aléatoire. 

Les missions multiples ne relient pas parfaitement les individus, mais elles relient des individus qui autrement sont délaissés dans la structure traditionnelle d'une mission accréditée pour un unique pays. Sa structure est presque similaire à celle du réseau des missions uniques, et est même parfois plus cohésif et connecté. Certaines nations dépendent beaucoup des accréditations multiples, sur le nombre total de liens maintenus. Il ne faut pas disqualifier l'importance de ce genre de mission qui permet d'augmenter sa connection au reste du monde, à l'insu de la "puissance" d'un lien. 

Centralité d'intermédiarité contre intermédiarité "réelle" des nations du monde: peu de différence en terme de corrélation.  

Processus qui s'est développé graduellement et a trouvé son audience. La trajectoire des missions multiples me fait penser que ces dernières atteignent, voire dépassent, la portée des missions uniques.
